config:
  cluster:
    enabled: false # Enable clustering
  jetstream:
    enabled: true # Enable JetStream
    fileStore:
      enabled: true
      dir: /data
      pvc:
        enabled: true
        size: 5Gi
        storageClassName: "oci-block-storage"
  nats:
    port: 4222 # Default NATS port
    tls:
      enabled: false # Set to true if you want to enable TLS

  # The chart will create a PVC for the NATS file store (see 'fileStore.pvc' above). If you prefer a pre-existing claim, set 'fileStore.pvc.enabled=false' and define a PVC in cluster-resources with that name.
  extraVolumeMounts:
    - name: jetstream-storage
      mountPath: /data

resources:
  limits:
    memory: 128Mi
    cpu: 100m
  requests:
    memory: 64Mi
    cpu: 50m

service:
  type: ClusterIP
